-- MySQL Script generated by MySQL Workbench
-- Sat Sep  9 20:08:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apeliido` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Teléfono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Valor` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proteína`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proteína` (
  `idProteína` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(200) NULL,
  PRIMARY KEY (`idProteína`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrada` (
  `idEntrada` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(200) NULL,
  PRIMARY KEY (`idEntrada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Base` (
  `idBase` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(200) NULL,
  PRIMARY KEY (`idBase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bebida` (
  `idBebida` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(200) NULL,
  PRIMARY KEY (`idBebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Almuerzo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Almuerzo` (
  `idAlmuerzo` INT NOT NULL,
  `Proteína_idProteína` INT NOT NULL,
  `Entrada_idEntrada` INT NOT NULL,
  `Base_idBase` INT NOT NULL,
  `Bebida_idBebida` INT NOT NULL,
  PRIMARY KEY (`idAlmuerzo`, `Proteína_idProteína`, `Entrada_idEntrada`, `Base_idBase`, `Bebida_idBebida`),
  INDEX `fk_Almuerzo_Proteína_idx` (`Proteína_idProteína` ASC) VISIBLE,
  INDEX `fk_Almuerzo_Entrada1_idx` (`Entrada_idEntrada` ASC) VISIBLE,
  INDEX `fk_Almuerzo_Base1_idx` (`Base_idBase` ASC) VISIBLE,
  INDEX `fk_Almuerzo_Bebida1_idx` (`Bebida_idBebida` ASC) VISIBLE,
  CONSTRAINT `fk_Almuerzo_Proteína`
    FOREIGN KEY (`Proteína_idProteína`)
    REFERENCES `mydb`.`Proteína` (`idProteína`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Almuerzo_Entrada1`
    FOREIGN KEY (`Entrada_idEntrada`)
    REFERENCES `mydb`.`Entrada` (`idEntrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Almuerzo_Base1`
    FOREIGN KEY (`Base_idBase`)
    REFERENCES `mydb`.`Base` (`idBase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Almuerzo_Bebida1`
    FOREIGN KEY (`Bebida_idBebida`)
    REFERENCES `mydb`.`Bebida` (`idBebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Almuerzo_has_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Almuerzo_has_Pedido` (
  `Almuerzo_idAlmuerzo` INT NOT NULL,
  `Almuerzo_Proteína_idProteína` INT NOT NULL,
  `Almuerzo_Entrada_idEntrada` INT NOT NULL,
  `Almuerzo_Base_idBase` INT NOT NULL,
  `Almuerzo_Bebida_idBebida` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Cantidad_Almuerzos` TINYINT(20) NOT NULL,
  PRIMARY KEY (`Almuerzo_idAlmuerzo`, `Almuerzo_Proteína_idProteína`, `Almuerzo_Entrada_idEntrada`, `Almuerzo_Base_idBase`, `Almuerzo_Bebida_idBebida`, `Pedido_idPedido`),
  INDEX `fk_Almuerzo_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Almuerzo_has_Pedido_Almuerzo1_idx` (`Almuerzo_idAlmuerzo` ASC, `Almuerzo_Proteína_idProteína` ASC, `Almuerzo_Entrada_idEntrada` ASC, `Almuerzo_Base_idBase` ASC, `Almuerzo_Bebida_idBebida` ASC) VISIBLE,
  CONSTRAINT `fk_Almuerzo_has_Pedido_Almuerzo1`
    FOREIGN KEY (`Almuerzo_idAlmuerzo` , `Almuerzo_Proteína_idProteína` , `Almuerzo_Entrada_idEntrada` , `Almuerzo_Base_idBase` , `Almuerzo_Bebida_idBebida`)
    REFERENCES `mydb`.`Almuerzo` (`idAlmuerzo` , `Proteína_idProteína` , `Entrada_idEntrada` , `Base_idBase` , `Bebida_idBebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Almuerzo_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
